/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;

/**
 *
 * @author SAM OTNAY
 */
public class datasiswa extends javax.swing.JFrame {

    /**
     * Creates new form DATASISWAKLS9A
     */
    public datasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nis = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        agama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enis = new javax.swing.JTextField();
        enama = new javax.swing.JTextField();
        cbagama = new javax.swing.JComboBox<>();
        hasil = new javax.swing.JTextField();
        rb_pria = new javax.swing.JRadioButton();
        rb_wanita = new javax.swing.JRadioButton();
        hasil2 = new javax.swing.JTextField();
        cbpencak = new javax.swing.JCheckBox();
        cbvokal = new javax.swing.JCheckBox();
        cbesport = new javax.swing.JCheckBox();
        cbpramuka = new javax.swing.JCheckBox();
        cbpidato = new javax.swing.JCheckBox();
        cbdrumband = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arearesume = new javax.swing.JTextArea();
        bclear = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        bproses = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nis.setForeground(new java.awt.Color(255, 255, 255));
        nis.setText("NIS");
        getContentPane().add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 61, -1, -1));

        nama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("NAMA");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 101, -1, -1));

        agama.setBackground(new java.awt.Color(153, 153, 0));
        agama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agama.setForeground(new java.awt.Color(255, 255, 255));
        agama.setText("AGAMA");
        getContentPane().add(agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 141, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JENIS KELAMIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EXTRAKURIKULER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 259, -1, -1));
        getContentPane().add(enis, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 58, 174, -1));
        getContentPane().add(enama, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 98, 174, -1));

        cbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Aliran Kepercayaan" }));
        getContentPane().add(cbagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 138, 104, -1));
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 138, 173, -1));

        rb_pria.setText("Laki Laki");
        getContentPane().add(rb_pria, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 188, -1, -1));

        rb_wanita.setText("Perempuan");
        rb_wanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_wanitaActionPerformed(evt);
            }
        });
        getContentPane().add(rb_wanita, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 188, -1, -1));
        getContentPane().add(hasil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 187, 122, -1));

        cbpencak.setText("Pencak Silat");
        getContentPane().add(cbpencak, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 257, -1, -1));

        cbvokal.setText("Olah Vokal");
        getContentPane().add(cbvokal, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 289, -1, -1));

        cbesport.setText("Esport MLBB");
        getContentPane().add(cbesport, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 327, -1, -1));

        cbpramuka.setText("Pramuka");
        getContentPane().add(cbpramuka, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 257, -1, -1));

        cbpidato.setText("Pidato");
        getContentPane().add(cbpidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 289, -1, -1));

        cbdrumband.setText("Drumband");
        getContentPane().add(cbdrumband, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 327, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("KETERANGAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 64, -1, -1));

        arearesume.setColumns(20);
        arearesume.setRows(5);
        jScrollPane1.setViewportView(arearesume);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 85, 194, 262));

        bclear.setText("Clear");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        getContentPane().add(bclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 365, -1, -1));

        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        getContentPane().add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 365, -1, -1));

        bproses.setText("Proses");
        bproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprosesActionPerformed(evt);
            }
        });
        getContentPane().add(bproses, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 365, -1, -1));

        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 75, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAM OTNAY\\Downloads\\KODING APLIKASI.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
        enis.setText("");
        enama.setText("");
        hasil.setText("");
        hasil2.setText("");
        arearesume.setText("");
    }//GEN-LAST:event_bclearActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bexitActionPerformed

    private void bprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprosesActionPerformed
        // TODO add your handling code here:
        int indexcombo;
        String pilihan;
        char kelamin;
        String daftarextrakurikuler = "";

        indexcombo = cbagama.getSelectedIndex();
        pilihan = (String) cbagama.getSelectedItem();

        hasil.setText(pilihan);

        kelamin = 'P';

        if (rb_pria.isSelected()) {
            kelamin = 'L';
        } else {
            kelamin = 'P';
        }
        hasil2.setText(String.valueOf(kelamin));

        if (cbpencak.isSelected()) {
            daftarextrakurikuler += cbpencak.getText() + "\n";
        }
        if (cbvokal.isSelected()) {
            daftarextrakurikuler += cbvokal.getText() + "\n";
        }
        if (cbesport.isSelected()) {
            daftarextrakurikuler += cbesport.getText() + "\n";
        }
        if (cbpramuka.isSelected()) {
            daftarextrakurikuler += cbpramuka.getText() + "\n";
        }
        if (cbpidato.isSelected()) {
            daftarextrakurikuler += cbpidato.getText() + "\n";
        }
        if (cbdrumband.isSelected()) {
            daftarextrakurikuler += cbdrumband.getText() + "\n";
        }

        arearesume.setText(
                "NIS: " + enis.getText() + "\n"
                + "NAMA: " + enama.getText() + "\n"
                + "AGAMA: " + pilihan + "\n"
                + "KELAMIN: " + kelamin + "\n"
                + "EXTRAKURIKULER: " + daftarextrakurikuler + "\n");

    }//GEN-LAST:event_bprosesActionPerformed

    private void rb_wanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_wanitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_wanitaActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        masuk lg = new masuk();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(masuk.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agama;
    private javax.swing.JTextArea arearesume;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bproses;
    private javax.swing.JComboBox<String> cbagama;
    private javax.swing.JCheckBox cbdrumband;
    private javax.swing.JCheckBox cbesport;
    private javax.swing.JCheckBox cbpencak;
    private javax.swing.JCheckBox cbpidato;
    private javax.swing.JCheckBox cbpramuka;
    private javax.swing.JCheckBox cbvokal;
    private javax.swing.JTextField enama;
    private javax.swing.JTextField enis;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField hasil2;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nis;
    private javax.swing.JRadioButton rb_pria;
    private javax.swing.JRadioButton rb_wanita;
    // End of variables declaration//GEN-END:variables
}
